modules/empresa/controllers/VentasController.php
<?php

namespace app\modules\empresa\controllers;

use app\helper\AppHelper;
use app\models\Afiliado;
use app\models\CompraAfiliado;
use app\models\CompraAfiliadoPuntos;
use app\models\search\CompraAfiliadoPuntosSearch;
use app\models\search\CompraAfiliadoSearch;
use Yii;
use yii\data\ArrayDataProvider;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * VentasController implements the CRUD actions for CompraAfiliado model.
 */
class VentasController extends BaseEmpresaController
{
  public function behaviors()
  {
    return [
      'verbs' => [
        'class' => VerbFilter::className(),
        'actions' => [
          'delete' => ['post'],
        ],
      ],
      'access' => [
        'class' => AccessControl::className(),
        'rules' => [
          [
            'allow' => true,
            'actions' => ['index', 'view', 'create', 'update', 'delete','findcliente'],
            'roles' => [AppHelper::ADMIN_EMPRESA]
          ],
          [
            'allow' => false
          ]
        ]
      ]
    ];
  }

  /**
   * Lists all CompraAfiliado models.
   * @return mixed
   */
  public function actionIndex()
  {
    $searchModel = new CompraAfiliadoSearch([
      'empresa_id' => $this->empresa->id,
      'fecha' => date('Y-m-01'),
      'fecha_hasta' => date('Y-m-d'),
    ]);
    $searchModel->prepareCompraAfiliado(Yii::$app->request->queryParams);
    $dataProvider = $searchModel->search();

    return $this->render('index', [
      'searchModel' => $searchModel,
      'dataProvider' => $dataProvider,
    ]);
  }

  /**
   * Displays a single CompraAfiliado model.
   * @param integer $id
   * @return mixed
   */
  public function actionView($id)
  {
    $model = $this->findModel($id);
    return $this->render('view', [
      'model' => $this->findModel($id),
    ]);
  }

  /**
   * Creates a new CompraAfiliado model.
   * If creation is successful, the browser will be redirected to the 'view' page.
   * @return mixed
   */
  public function actionCreate()
  {
    $model = new CompraAfiliado();

    if ($model->loadAll(Yii::$app->request->post(), ['*']) && $model->saveAll(['*'])) {
      return $this->redirect(['view', 'id' => $model->id]);
    } else {
      return $this->render('create', [
        'model' => $model,
      ]);
    }
  }

  /**
   * Updates an existing CompraAfiliado model.
   * If update is successful, the browser will be redirected to the 'view' page.
   * @param integer $id
   * @return mixed
   */
  public function actionUpdate($id)
  {
    $model = $this->findModel($id);

    if ($model->loadAll(Yii::$app->request->post(), ['*']) && $model->saveAll(['*'])) {
      return $this->redirect(['view', 'id' => $model->id]);
    } else {
      return $this->render('update', [
        'model' => $model,
      ]);
    }
  }

  /**
   * Deletes an existing CompraAfiliado model.
   * If deletion is successful, the browser will be redirected to the 'index' page.
   * @param integer $id
   * @return mixed
   */
  public function actionDelete($id)
  {
    $this->findModel($id)->deleteWithRelated();

    return $this->redirect(['index']);
  }


  /**
   * Finds the CompraAfiliado model based on its primary key value.
   * If the model is not found, a 404 HTTP exception will be thrown.
   * @param integer $id
   * @return CompraAfiliado the loaded model
   * @throws NotFoundHttpException if the model cannot be found
   */
  protected function findModel($id)
  {
    if (($model = CompraAfiliado::findOne($id)) !== null) {
      return $model;
    } else {
      throw new NotFoundHttpException('The requested page does not exist.');
    }
  }

  public function actionFindcliente($query)
  {
    Yii::$app->response->format = Response::FORMAT_JSON;
    return Afiliado::find()
      ->select(['label' => 'CONCAT(usuario.documento," - ",usuario.nombres)', 'afiliado.id','usuario_id'])
      ->joinWith(['usuario'])
      ->where(['Like', 'usuario.nombres', $query])
      ->orWhere(['like', 'usuario.documento', $query])
      ->asArray()
      ->all();
  }
}

modules/empresa/views/ventas/_data_ventas.php
<?php
/**
 * Created by Jhon J Toloza.
 * User: jhon
 * Date: 28/09/17
 * Time: 06:11 PM
 * @var $data \yii\data\ActiveDataProvider
 * @var $this \yii\web\View
 */

use kartik\export\ExportMenu;
use kartik\grid\GridView;

$gridColumn = [
  ['class' => 'yii\grid\SerialColumn'],
  'fecha:datetime',
  'monto:currency',
  [
    'attribute' => 'monto_cobra_empresa',
    'label' => 'Cuota publicitaria',
    'format' => 'currency'
  ],
  [
    'attribute' => 'comentario',
    'label' => 'Factura',
  ],
  [
    'attribute' => 'empleado_id',
    'label' => 'Empleado',
    'value' => function (\app\models\CompraAfiliado $model) {
      return $model->empleado->usuario->nombres;
    },
  ],
];
?>
<?= GridView::widget([
  'dataProvider' => $data,
  'columns' => $gridColumn,
  'pjax' => true,
  'pjaxSettings' => ['options' => ['id' => 'kv-pjax-container-compra-afiliado']],
  'panel' => [
    'type' => GridView::TYPE_PRIMARY,
    'heading' => '<span class="glyphicon glyphicon-book"></span>  ' . \yii\helpers\Html::encode($this->title),
  ],
  'export' => false,
  'toolbar' => [
    '{export}',
    ExportMenu::widget([
      'dataProvider' => $data,
      'columns' => $gridColumn,
      'target' => ExportMenu::TARGET_BLANK,
      'fontAwesome' => true,
      'dropdownOptions' => [
        'label' => 'Full',
        'class' => 'btn btn-default',
        'itemsBefore' => [
          '<li class="dropdown-header">Exportar toda la información</li>',
        ],
      ],
      'exportConfig' => [
        ExportMenu::FORMAT_PDF => false
      ]
    ]),
  ],
]); ?>

modules/empresa/views/ventas/_data_ventas_puntos.php
<?php
/**
 * Created by Jhon J Toloza.
 * User: jhon
 * Date: 28/09/17
 * Time: 06:11 PM
 * @var $data \yii\data\ActiveDataProvider
 * @var $this \yii\web\View
 */

use kartik\export\ExportMenu;
use kartik\grid\GridView;

$gridColumn = [
  ['class' => 'yii\grid\SerialColumn'],
  'fecha:datetime',
  'monto:currency',
  [
    'attribute' => 'comentario',
    'label' => 'Factura',
  ],
  [
    'attribute' => 'empleado_id',
    'label' => 'Empleado',
    'value' => function (\app\models\CompraAfiliadoPuntos $model) {
      return $model->empleado->usuario->nombres;
    },
  ],
];
?>
<?= GridView::widget([
  'dataProvider' => $data,
  'columns' => $gridColumn,
  'pjax' => true,
  'pjaxSettings' => ['options' => ['id' => 'kv-pjax-container-compra-afiliado']],
  'panel' => [
    'type' => GridView::TYPE_PRIMARY,
    'heading' => '<span class="glyphicon glyphicon-book"></span>  ' . \yii\helpers\Html::encode($this->title),
  ],
  'export' => false,
  'toolbar' => [
    '{export}',
    ExportMenu::widget([
      'dataProvider' => $data,
      'columns' => $gridColumn,
      'target' => ExportMenu::TARGET_BLANK,
      'fontAwesome' => true,
      'dropdownOptions' => [
        'label' => 'Full',
        'class' => 'btn btn-default',
        'itemsBefore' => [
          '<li class="dropdown-header">Exportar toda la información</li>',
        ],
      ],
      'exportConfig' => [
        ExportMenu::FORMAT_PDF => false
      ]
    ]),
  ],
]); ?>

modules/empresa/views/ventas/_detail.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use kartik\grid\GridView;

/* @var $this yii\web\View */
/* @var $model app\models\CompraAfiliado */

?>
<div class="compra-afiliado-view">

    <div class="row">
        <div class="col-sm-9">
            <h2><?= Html::encode($model->id) ?></h2>
        </div>
    </div>

    <div class="row">
<?php 
    $gridColumn = [
        'fecha',
        'monto',
        'monto_cobra_empresa',
        'puntos',
        [
            'attribute' => 'afiliado.id',
            'label' => 'Afiliado',
        ],
        [
            'attribute' => 'empleado.id',
            'label' => 'Empleado',
        ],
    ];
    echo DetailView::widget([
        'model' => $model,
        'attributes' => $gridColumn
    ]); 
?>
    </div>
</div>

modules/empresa/views/ventas/_expand.php
<?php

use kartik\tabs\TabsX;
use yii\helpers\Html;

$items = [
  [
    'label' => '<i class="glyphicon glyphicon-book"></i> ' . Html::encode('CompraAfiliado'),
    'content' => $this->render('_detail', [
      'model' => $model,
    ]),
  ],
];
echo TabsX::widget([
  'items' => $items,
  'position' => TabsX::POS_ABOVE,
  'encodeLabels' => false,
  'class' => 'tes',
  'pluginOptions' => [
    'bordered' => true,
    'sideways' => true,
    'enableCache' => false
  ],
]);
?>

modules/empresa/views/ventas/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\CompraAfiliado */
/* @var $form yii\widgets\ActiveForm */

?>

<div class="compra-afiliado-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->errorSummary($model); ?>

    <?= $form->field($model, 'fecha')->widget(\kartik\datecontrol\DateControl::classname(), [
        'type' => \kartik\datecontrol\DateControl::FORMAT_DATETIME,
        'saveFormat' => 'php:Y-m-d H:i:s',
        'ajaxConversion' => true,
        'options' => [
            'pluginOptions' => [
                'placeholder' => 'Choose Fecha',
                'autoclose' => true,
            ]
        ],
    ]); ?>

    <?= $form->field($model, 'monto')->textInput(['placeholder' => 'Monto']) ?>

    <?= $form->field($model, 'monto_cobra_empresa')->textInput(['placeholder' => 'Monto Cobra Empresa']) ?>

    <?= $form->field($model, 'puntos')->textInput(['placeholder' => 'Puntos']) ?>

    <?= $form->field($model, 'afiliado_id')->widget(\kartik\widgets\Select2::classname(), [
        'data' => \yii\helpers\ArrayHelper::map(\app\models\Afiliado::find()->orderBy('id')->asArray()->all(), 'id', 'id'),
        'options' => ['placeholder' => 'Choose Afiliado'],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ]); ?>

    <?= $form->field($model, 'empleado_id')->widget(\kartik\widgets\Select2::classname(), [
        'data' => \yii\helpers\ArrayHelper::map(\app\models\Empleado::find()->orderBy('id')->asArray()->all(), 'id', 'id'),
        'options' => ['placeholder' => 'Choose Empleado'],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ]); ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/empresa/views/ventas/_script.php
<?php
use yii\helpers\Url;

?>
<script>
    function addRow<?= $class ?>() {
        var data = $('#add-<?= $relID?> :input').serializeArray();
        data.push({name: '_action', value : 'add'});
        $.ajax({
            type: 'POST',
            url: '<?php echo Url::to(['add-'.$relID]); ?>',
            data: data,
            success: function (data) {
                $('#add-<?= $relID?>').html(data);
            }
        });
    }
    function delRow<?= $class ?>(id) {
        $('#add-<?= $relID?> tr[data-key=' + id + ']').remove();
    }
</script>

modules/empresa/views/ventas/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\CompraAfiliadoSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="form-compra-afiliado-search">

  <?php $form = ActiveForm::begin([
    'action' => ['index'],
    'method' => 'get',
    'fieldConfig' => [
      'options' => ['class' => 'col-lg-4']
    ]
  ]); ?>

  <?= $form->field($model, 'fecha')->widget(\kartik\date\DatePicker::className(), [
    'pluginOptions' => [
      'placeholder' => 'Seleccione Fecha',
      'format' => 'yyyy-mm-dd',
      'todayHighlight' => true,
      'autoclose' => true,
    ]
  ]); ?>

  <?= $form->field($model, 'fecha_hasta')->widget(\kartik\date\DatePicker::className(), [

    'pluginOptions' => [
      'placeholder' => 'Seleccione Fecha',
      'format' => 'yyyy-mm-dd',
      'todayHighlight' => true,
      'autoclose' => true,
    ]
  ]); ?>

  <?= $form->field($model, 'empleado_id')->widget(\kartik\widgets\Select2::classname(), [
    'data' => \yii\helpers\ArrayHelper::map(\app\models\Empleado::find()
      ->where(['empresa_id' => Yii::$app->controller->empresa->id])
      ->joinWith('usuario')
      ->orderBy('id')->all(), 'id', 'usuario.nombres'),
    'options' => ['placeholder' => 'Seleccione Empleado'],
    'pluginOptions' => [
      'allowClear' => true
    ],
  ]); ?>

  <?= $form->field($model,'comentario')->label('N° factura') ?>

  <?= $form->field($model,'tipo_compra')->label('Tipo de compra')
  ->dropDownList([''=>'Todo','1'=>'Efectivo','2'=>'Puntos'])?>

  <?= $form->field($model, 'afiliado_id', [
    'template' => "{label}\n{input}\n{auto}\n{hint}\n{error}",
    'parts' => [
      '{auto}' =>
        \yii\jui\AutoComplete::widget([
          'name' => 'cliente',
          'clientOptions' => [
            'source' => new \yii\web\JsExpression('
                                        function(request,response){
                                            var val = $("input[name=\\"cliente\\"]");
                                                $.getJSON("' . \yii\helpers\Url::to(['ventas/findcliente']) . '",{query:val.val()},function(data){
                                                response(data);
                                            });
                                        }'),
            'select' =>
              new \yii\web\JsExpression("function(event,ui){
                                            var client_info = $('#client_info');
                                            var input = $('#".Html::getInputId($model,'afiliado_id')."');
                                            input.val(ui.item.id);
                                            return false;
                                        }")
          ],
          'options' => [
            'class' => 'form-control'
          ]
        ])
    ]
  ])->hiddenInput() ?>

  <div class="form-group clearfix">
    <?= Html::submitButton('Buscar', ['class' => 'btn btn-primary']) ?>
  </div>

  <?php ActiveForm::end(); ?>

</div>
<div class="clearfix"></div>

modules/empresa/views/ventas/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\CompraAfiliado */

$this->title = 'Create Compra Afiliado';
$this->params['breadcrumbs'][] = ['label' => 'Compra Afiliados', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="compra-afiliado-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/empresa/views/ventas/index.php
<?php

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\CompraAfiliadoSearch */
/* @var $searchModelPuntos app\models\search\CompraAfiliadoPuntosSearch */

/* @var $dataProvider yii\data\ActiveDataProvider */

use kartik\export\ExportMenu;
use kartik\grid\GridView;
use yii\helpers\Html;

$this->title = 'Ventas a Afiliados';
$this->params['breadcrumbs'][] = $this->title;
$search = "$('.search-button').click(function(){
	$('.search-form').toggle(1000);
	return false;
});";
$this->registerJs($search);
?>
<div class="compra-afiliado-index">
  <p>
    <?= Html::a('Busqueda avanzada', '#', ['class' => 'btn btn-info search-button']) ?>
  </p>
  <div class="search-form" style="display:none">
    <?= $this->render('_search', ['model' => $searchModel]); ?>
  </div>
  <?php
  $gridColumn = [
    ['class' => 'yii\grid\SerialColumn'],
    'afiliado.usuario.nombres',
    'empleado.usuario.nombres',
    'fecha:datetime',
    'monto:currency',
    [
      'attribute' => 'monto_cobra_empresa',
      'label' => 'Cuota publicitaria',
      'format' => 'currency'
    ],
    'puntos:currency',
    [
      'attribute' => 'comentario',
      'label' => 'Factura',
    ],
    'pago_puntos:boolean'
  ];
  ?>
  <?= GridView::widget([
    'dataProvider' => $dataProvider,
    'columns' => $gridColumn,
    'pjax' => true,
    'pjaxSettings' => ['options' => ['id' => 'kv-pjax-container-compra-afiliado']],
    'panel' => [
      'type' => GridView::TYPE_PRIMARY,
      'heading' => '<span class="glyphicon glyphicon-book"></span>  ' . \yii\helpers\Html::encode($this->title),
    ],
    'export' => false,
    'toolbar' => [
      '{export}',
      ExportMenu::widget([
        'dataProvider' => $dataProvider,
        'columns' => $gridColumn,
        'target' => ExportMenu::TARGET_BLANK,
        'fontAwesome' => true,
        'dropdownOptions' => [
          'label' => 'Full',
          'class' => 'btn btn-default',
          'itemsBefore' => [
            '<li class="dropdown-header">Exportar toda la información</li>',
          ],
        ],
        'exportConfig' => [
          ExportMenu::FORMAT_PDF => false
        ]
      ]),
    ],
  ]); ?>
</div>

modules/empresa/views/ventas/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\CompraAfiliado */

$this->title = 'Update Compra Afiliado: ' . ' ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Compra Afiliados', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="compra-afiliado-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/empresa/views/ventas/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use kartik\grid\GridView;

/* @var $this yii\web\View */
/* @var $model app\models\CompraAfiliado */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Compra Afiliados', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="compra-afiliado-view">

    <div class="row">
        <div class="col-sm-9">
            <h2><?= 'Compra Afiliado'.' '. Html::encode($this->title) ?></h2>
        </div>
        <div class="col-sm-3" style="margin-top: 15px">
            
            <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
            <?= Html::a('Delete', ['delete', 'id' => $model->id], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => 'Are you sure you want to delete this item?',
                    'method' => 'post',
                ],
            ])
            ?>
        </div>
    </div>

    <div class="row">
<?php 
    $gridColumn = [
        'fecha',
        'monto',
        'monto_cobra_empresa',
        'puntos',
        [
            'attribute' => 'afiliado.id',
            'label' => 'Afiliado',
        ],
        [
            'attribute' => 'empleado.id',
            'label' => 'Empleado',
        ],
    ];
    echo DetailView::widget([
        'model' => $model,
        'attributes' => $gridColumn
    ]); 
?>
    </div>
</div>