modules/admin/controllers/TaxiAppController.php
<?php
/**
 * Created by PhpStorm.
 * User: jhon
 * Date: 15/02/19
 * Time: 11:31 AM
 */

namespace app\modules\admin\controllers;


use app\models\AppHelper;
use app\models\Driver;
use app\models\DriverCategory;
use app\models\DriverCategoryState;
use app\models\Usuario;
use Kreait\Firebase\Factory;
use Yii;
use yii\data\ActiveDataProvider;
use yii\helpers\Html;
use yii\helpers\Json;
use yii\helpers\Url;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\UploadedFile;
use yii\widgets\ActiveForm;

class TaxiAppController extends Controller
{
  public function actionList()
  {
    $modelSearch = new Driver([
       'scenario' => 'search'
    ]);
    $dataProvider = $modelSearch->search(Yii::$app->request->queryParams);
    if (Yii::$app->request->post('hasEditable')) {
      $model = Driver::findOne(Yii::$app->request->post('editableKey'));
      $model->load(Yii::$app->request->post($model->formName())[Yii::$app->request->post('editableIndex')], '');
      $model->save();
      $attr = Yii::$app->request->post('editableAttribute');
      if ($attr == 'active')
        return Json::encode(['output' => Yii::$app->formatter->asBoolean($model->{$attr})]);
      else if ($attr == 'porcent')
        return Json::encode(['output' => Yii::$app->formatter->asPercent($model->{$attr})]);
      else
        return Json::encode(['output' => $model->{$attr}]);
    }
    return $this->render('list', [
       'data' => $dataProvider,
       'modelSearch' => $modelSearch
    ]);
  }

  public function actionUpdateTelefono()
  {
    $data = Yii::$app->request->post('data');
    foreach ($data as $key => $datum) {
      if ($key == 0){
        Yii::info($datum);
      }
      $user = Usuario::findOne(['access_token' => $datum['uid']]);
      if ($user and $user->driver) {
        //if ($user->driver->telefono == null) {
          $user->driver->telefono = $datum['telefono'];
          $user->driver->save(false);
        //}
      }
    }
  }

  public function actionViewDriver($id)
  {
    $driver = Driver::findOne($id);
    if ($driver->load(Yii::$app->request->post())) {
      if ($driver->save()) {
        Yii::$app->session->setFlash('success', 'Guardado correctamente');
      }
    }
    return $this->render('view-driver', [
       'model' => $driver
    ]);
  }

  public function actionCategories()
  {
    if (Yii::$app->request->post('hasEditable')) {
      $attr = Yii::$app->request->post('editableAttribute');
      $model = DriverCategory::findOne(Yii::$app->request->post('editableKey'));
      if ($model != null) {
        $model->load(Yii::$app->request->post($model->formName())[Yii::$app->request->post('editableIndex')], '');
        $model->save();
        Yii::info(strpos('porcent', $attr));
        if ($attr == 'porcent' || $attr == 'porcent_affiliate') {
          return Json::encode(['output' => Yii::$app->formatter->asPercent($model->{$attr})]);
        } else {
          return Json::encode(['output' => $model->name]);
        }
      }
    }
    return $this->render('categories', [
       'data' => new ActiveDataProvider([
          'query' => DriverCategory::find()
       ])
    ]);
  }

  public function actionUpdateCategoryFile()
  {
    $model = DriverCategory::findOne(Yii::$app->request->post('editableKey'));
    $attr = Yii::$app->request->post('editableAttribute');
    $files = UploadedFile::getInstancesByName('DriverCategory[' . Yii::$app->request->post('editableIndex') . '][' . $attr . ']');
    if ($model and !empty($files)) {
      $file = $files[0];
      $folder = AppHelper::obtenerDirectorio('driver-category/icon');
      $model->{$attr} = "$folder/" . Yii::$app->security->generateRandomString(5)
         . '.' . $file->extension;
      $model->save(false);
      $file->saveAs($model->{$attr});
      return Json::encode(['output' => Html::img(Url::to("@web/" . $model->{$attr}))]);
    }
    throw new BadRequestHttpException();
  }

  public function actionStateCategories()
  {
    if (Yii::$app->request->post('hasEditable')) {
      $attr = Yii::$app->request->post('editableAttribute');
      $model = DriverCategoryState::findOne(Yii::$app->request->post('editableKey'));
      if ($model != null) {
        $model->load(Yii::$app->request
           ->post($model->formName())[Yii::$app->request->post("editableIndex")], '');
        $model->save();
        Driver::updateAll(['porcent' => $model->porcent], ['departamento_id' => $model->departamento_id]);
        return Json::encode(['output' => Yii::$app->formatter->asPercent($model->{$attr})]);
      }
    }
    $model = new DriverCategoryState();
    $query = DriverCategoryState::find();
    if ($model->load(Yii::$app->request->post())) {
      $query->andFilterCompare('driver_category_id', $model->driver_category_id)
         ->andFilterCompare('departamento_id', $model->departamento_id);
    }
    return $this->render('category_states', [
       'model' => $model,
       'data' => new ActiveDataProvider([
          'query' => $query
       ])
    ]);
  }

  public function actionAddStateCategory()
  {
    $model = new DriverCategoryState();
    if ($model->load(Yii::$app->request->post())) {
      if (Yii::$app->request->isAjax) {
        Yii::$app->response->format = 'json';
        return ActiveForm::validate($model);
      }
      $model->save();
      return $this->redirect(['taxi-app/state-categories']);
    }
    throw new BadRequestHttpException();
  }

  public function actionDetail()
  {
    if (($key = Yii::$app->request->post('expandRowKey')) !== false) {
      return $this->renderPartial('_detail_list', ['model' => Driver::findOne($key)]);
    }
    throw new BadRequestHttpException();
  }

  public function actionUpdatePassword($id){
    $driver = Driver::findOne($id);
    Yii::info(file_get_contents('clave.json'));
    $firebase = (new Factory())
//       ->withHttpClientConfig([
//          'debug' => true
//       ])
       ->withServiceAccount('clave.json')
       ->create();
    $auth = $firebase->getAuth();
    $user = $auth->getUser('oN40rBOFdzYk89XiX9GH2CuhQbW2');
    Yii::info($user);
    //$auth->changeUserPassword('oN40rBOFdzYk89XiX9GH2CuhQbW2', '123456');
    //return $this->redirect(['taxi-app/view-driver', 'id' => $driver->id]);
  }

  public function actionActive()
  {

  }
}

modules/admin/views/taxi-app/_detail_list.php
<?php

/**
 * Created by PhpStorm.
 * User: jhon
 * Date: 15/02/19
 * Time: 11:51 AM
 */

/* @var $this \yii\web\View */
/* @var $model null|\app\models\Driver */
$data = \yii\helpers\Json::decode($model->car_info);
if ($data == null)
  $data = [];

$value = function ($property) use ($data) {
  if (isset($data[$property])) {
    Yii::info($data[$property]);
    return $data[$property];
  } else {
    return 'No Especificado';
  }
}

?>
<div class="col-sm-6">
  <?= \yii\widgets\DetailView::widget([
    'model' => $data,
    'attributes' => [
      ['label' => 'Marca', 'value' => $value('brand')],
      ['label' => 'Modelo', 'value' => $value('model')],
      ['label' => 'Placa', 'value' => $value('plate')],
      ['label' => 'Documento cargado', 'value' =>
        \yii\helpers\Html::a($value('doc_url'), $value('doc_url'), ['target' => '_black']),
        'format' => 'raw'
      ],
    ]
  ]) ?>
</div>

modules/admin/views/taxi-app/categories.php
<?php

/**
 * Created by PhpStorm.
 * User: jhon
 * Date: 18/02/19
 * Time: 12:24 PM
 */

/* @var $this \yii\web\View */
/* @var $data \app\models\DriverCategory[]|array */
$this->title = 'Categoria de autos';
?>
<?= \kartik\grid\GridView::widget([
  'dataProvider' => $data,
  'columns' => [
    'id',
    [
      'class' => 'kartik\grid\EditableColumn',
      'attribute' => 'icon',
      'editableOptions' => [
        'formOptions' => [
          'action' => ['update-category-file'],
          'options' => [
            'enctype' => 'multipart/form-data'
          ],
        ],
        'inputType' => \kartik\editable\Editable::INPUT_FILEINPUT,
        'options' => [
          'options' => ['accept' => 'image/*'],
          'pluginOptions' => [
            'showRemove' => false,
            'showUpload' => false,
          ]
        ],
      ],
      'value' => function (\app\models\DriverCategory $model) {
        return \yii\helpers\Html::img("@web/" . $model->icon);
      },
      'format' => 'raw',
      'header' => 'Icono de lista (50*50)',
    ],
    [
      'class' => 'kartik\grid\EditableColumn',
      'attribute' => 'icon_map',
      'editableOptions' => [
        'formOptions' => [
          'action' => ['update-category-file'],
          'options' => [
            'enctype' => 'multipart/form-data'
          ],
        ],
        'inputType' => \kartik\editable\Editable::INPUT_FILEINPUT,
        'options' => [
          'options' => ['accept' => 'image/*'],
          'pluginOptions' => [
            'showRemove' => false,
            'showUpload' => false,
          ]
        ],
      ],
      'value' => function (\app\models\DriverCategory $model) {
        return \yii\helpers\Html::img("@web/" . $model->icon_map);
      },
      'format' => 'raw',
      'header' => 'Icono del mapa (32*32)'
    ],
    [
      'class' => 'kartik\grid\EditableColumn',
      'attribute' => 'name',
    ],
    [
      'class' => 'kartik\grid\EditableColumn',
      'attribute' => 'porcent',
      'format' => 'percent',
      'enableSorting' => false,
      'editableOptions' => [
        'inputType' => \kartik\editable\Editable::INPUT_WIDGET,
        'widgetClass' => 'yii\widgets\MaskedInput',
        'options' => [
          'mask' => '0.9[9][9]'
        ]
      ]
    ],
    [
      'class' => 'kartik\grid\EditableColumn',
      'attribute' => 'porcent_affiliate',
      'format' => 'percent',
      'enableSorting' => false,
      'editableOptions' => [
        'inputType' => \kartik\editable\Editable::INPUT_WIDGET,
        'widgetClass' => 'yii\widgets\MaskedInput',
        'options' => [
          'mask' => '0.9[9][9]'
        ]
      ]
    ]
  ]
]) ?>

modules/admin/views/taxi-app/category_states.php
<?php

/**
 * Created by PhpStorm.
 * User: jhon
 * Date: 18/02/19
 * Time: 02:58 PM
 */

/* @var $this \yii\web\View */
/* @var $model \app\models\DriverCategoryState */
/* @var $data \yii\data\ActiveDataProvider */
$this->title = 'Porcentajes de categoria por departamento';
?>
<div class="panel panel-danger">
  <div class="panel-heading">
    <h2 class="panel-title">Asignar diferente porcentaje</h2>
  </div>
  <div class="panel-body">
    <?php $form = \yii\widgets\ActiveForm::begin([
      'action' => ['add-state-category'],
      'enableAjaxValidation' => true
    ]) ?>
    <?= $form->field($model, 'driver_category_id')->dropDownList(
      \yii\helpers\ArrayHelper::map(\app\models\DriverCategory::find()->all(), 'id', 'name'),
      ['prompt' => 'Seleccione']
    ) ?>
    <?= $form->field($model, 'departamento_id')->widget(\kartik\select2\Select2::class, [
      'data' => \yii\helpers\ArrayHelper::map(\app\models\Departamento::find()->all(), 'id', 'nombre'),
      'options' => ['prompt' => 'Seleccione'],
      'pluginOptions' => [
        'allowClear' => 'true'
      ]
    ]) ?>
    <?= $form->field($model, 'porcent')->widget(\yii\widgets\MaskedInput::class, [
      'mask' => '0.9[9][9]'
    ]) ?>
    <?= $form->field($model, 'porcent_affiliate')->widget(\yii\widgets\MaskedInput::class, [
      'mask' => '0.9[9][9]'
    ]) ?>
    <?= \yii\helpers\Html::submitButton('Guardar', ['class' => 'btn btn-primary']) ?>
    <?php \yii\widgets\ActiveForm::end() ?>
  </div>
</div>
<div class="panel panel-info">
  <div class="panel-heading">
    <h2 class="panel-title">Asignados</h2>
  </div>
  <div class="panel-body">
    <div class="row col-lg-12">
      <?php $form = \yii\widgets\ActiveForm::begin([
        'fieldConfig' => ['options' => ['class' => 'col-lg-6']],
        'action' => ['state-categories'],
        'enableClientScript' => false
      ]) ?>
      <?= $form->field($model, 'driver_category_id')->dropDownList(
        \yii\helpers\ArrayHelper::map(\app\models\DriverCategory::find()->all(), 'id', 'name'),
        ['prompt' => 'Seleccione']
      ) ?>
      <?= $form->field($model, 'departamento_id')
        ->widget(\kartik\select2\Select2::class, [
          'id' => 'departamento',
          'data' => \yii\helpers\ArrayHelper::map(\app\models\Departamento::find()->all(), 'id', 'nombre'),
          'options' => ['prompt' => 'Seleccione', 'id' => 'departamento'],
          'pluginOptions' => [
            'allowClear' => 'true'
          ]
        ]) ?>
      <?= \yii\helpers\Html::submitButton('Buscar', ['class' => 'btn btn-success']) ?>
      <?php \yii\widgets\ActiveForm::end() ?>
    </div>
    <div class=" col-lg-12 row">
      <?= \kartik\grid\GridView::widget([
        'dataProvider' => $data,
        'columns' => [
          'id', [
            'attribute' => 'departamento_id',
            'value' => 'departamento.nombre'
          ],
          [
            'attribute' => 'category_id',
            'value' => 'driverCategory.name'
          ],
          [
            'class' => 'kartik\grid\EditableColumn',
            'attribute' => 'porcent',
            'format' => 'percent',
            'enableSorting' => false,
            'editableOptions' => [
              'inputType' => \kartik\editable\Editable::INPUT_WIDGET,
              'widgetClass' => 'yii\widgets\MaskedInput',
              'options' => [
                'mask' => '0.9[9][9]'
              ]
            ]
          ],
          [
            'class' => 'kartik\grid\EditableColumn',
            'attribute' => 'porcent_affiliate',
            'format' => 'percent',
            'enableSorting' => false,
            'editableOptions' => [
              'inputType' => \kartik\editable\Editable::INPUT_WIDGET,
              'widgetClass' => 'yii\widgets\MaskedInput',
              'options' => [
                'mask' => '0.9[9][9]'
              ]
            ]
          ],
          [
            'header' => 'Borrar',
            'value' => function (\app\models\DriverCategoryState $model) {
              return \yii\helpers\Html::a('Borrar', ['taxi-app/delete-state-category', 'id' => $model->id],
                ['data-confirm' => 'Seguro desea eliminar esta asignación', 'class' => 'btn btn-xs btn-danger']);
            },
            'format' => 'raw'
          ]
        ]
      ]) ?>
    </div>
  </div>
</div>

modules/admin/views/taxi-app/list.php
<?php

/**
 * Created by PhpStorm.
 * User: jhon
 * Date: 15/02/19
 * Time: 11:38 AM
 */

use kartik\export\ExportMenu;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $data \yii\data\ActiveDataProvider */
/* @var $modelSearch \app\models\Driver */
$search = "$('.search-button').click(function(){
	$('.search-form').toggle(1000);
	return false;
});";
$this->registerJs($search);
$this->title = 'Administración de taxistas';
$columns = [
   'id', [
      'class' => \kartik\grid\ExpandRowColumn::class,
      'value' => function () {
        return \kartik\grid\GridView::ROW_COLLAPSED;
      },
      'detailUrl' => \yii\helpers\Url::to(['taxi-app/detail'])
   ],
   [
      'class' => 'kartik\grid\EditableColumn',
      'attribute' => 'active',
      'format' => 'boolean',
      'editableOptions' => [
         'inputType' => \kartik\editable\Editable::INPUT_DROPDOWN_LIST,
         'data' => [
            '0' => 'Inactivo',
            '1' => 'Activo'
         ]
      ]
   ],
   ['label' => 'Nombre', 'attribute' => 'usuario.nombres'],
   ['label' => 'Categoria', 'attribute' => 'driverCategory.name'],
   ['label' => 'Saldo', 'attribute' => 'credits'],
   ['class' => 'kartik\grid\EditableColumn',
      'attribute' => 'porcent',
      'format' => 'percent',
      'enableSorting' => false,
      'editableOptions' => [
         'inputType' => \kartik\editable\Editable::INPUT_WIDGET,
         'widgetClass' => 'yii\widgets\MaskedInput',
         'options' => [
            'mask' => '0.9[9][9]'
         ]
      ]
   ],
   [
      'label' => 'Telefono',
      'value' => 'telefono',
   ],
    'credits',
    'departamento.nombre',
   [
      'label' => 'Opciones',
      'value' => function (\app\models\Driver $model) {
        return Html::a('VER', ['view-driver', 'id' => $model->id], ['class' => 'btn btn-default']);
      },
      'format' => 'raw'
   ]
];
?>
  <p>
    <?= Html::a('Busqueda', '#', ['class' => 'btn btn-info search-button']) ?>
  </p>
  <div class="col-lg-12 row">
    <div class="search-form" style="display:none">
      <?php $form = ActiveForm::begin([
         'action' => ['list'],
         'method' => 'get',
         'fieldConfig' => ['options' => ['class' => 'col-md-6']]
      ]) ?>
      <?= $form->field($modelSearch, 'usuario_id')->widget(\kartik\widgets\Select2::classname(), [
         'data' => \yii\helpers\ArrayHelper::map(\app\models\Usuario::find()
            ->orderBy('nombres')->asArray()->all(), 'id', function ($model) {
           return $model['nombres'] . ' - ' . $model['documento'];
         }),
         'options' => ['placeholder' => 'Usuario'],
         'pluginOptions' => [
            'allowClear' => true
         ],
      ]); ?>
      <?= $form->field($modelSearch, 'active')->dropDownList([
         '' => 'All',
         '1' => 'Solo activos',
         '0' => 'Solo inactivos'
      ]) ?>
      <?= $form->field($modelSearch, 'driver_category_id')->dropDownList(
         \yii\helpers\ArrayHelper::map(\app\models\DriverCategory::find()->orderBy('name')
            ->asArray()->all(), 'id', 'name'),
         ['prompt' => 'Seleccione la categoria']
      ) ?>
      <?= $form->field($modelSearch, 'departamento_id')->dropDownList(
         \yii\helpers\ArrayHelper::map(\app\models\Departamento::find()->orderBy('nombre')
            ->asArray()->all(), 'id', 'nombre'),
         ['prompt' => 'Seleccione departamento']
      ) ?>
      <div class="col-lg-12 row text-right">
        <?= \kartik\helpers\Html::submitButton('Buscar', ['class' => 'btn btn-primary']) ?>
      </div>
      <?php ActiveForm::end() ?>
    </div>
  </div>
  <div class="clearfix"></div>
<?= ExportMenu::widget([
   'dataProvider' => $data,
   'columns' => $columns
]) ?>
  <div class="clearfix"></div>
<?= \kartik\grid\GridView::widget([
   'dataProvider' => $data,
   'pager' => [
      'maxButtonCount' => 24
   ],
   'columns' => $columns
]) ?>
<?php
$this->registerJsFile('https://www.gstatic.com/firebasejs/5.8.4/firebase.js', [
   'position' => $this::POS_HEAD
]);
$this->registerJs('
 var config = {
    apiKey: "AIzaSyAf3s1qepgZT9W6BYv5NkhXw5IMONrsDCE",
    authDomain: "taxidriver-23cbd.firebaseapp.com",
    databaseURL: "https://taxidriver-23cbd.firebaseio.com",
    projectId: "taxidriver-23cbd",
    storageBucket: "taxidriver-23cbd.appspot.com",
    messagingSenderId: "927678779355"
  };
  firebase.initializeApp(config);', $this::POS_HEAD);
$this->registerJsFile("@web/js/getDatos.js", [
   'depends' => \yii\web\JqueryAsset::class
])
?>

modules/admin/views/taxi-app/view-driver.php
<?php


/* @var $this \yii\web\View */

/* @var $model null|\app\models\Driver */

use yii\helpers\Html;
use yii\web\JqueryAsset;

?>
  <div id="driver" class="panel panel-default" data-driver_id="<?= $model->usuario->access_token ?>">
    <div class="panel-body">
      <div class="col-md-6">
        <?= \yii\widgets\DetailView::widget([
           'model' => $model,
           'attributes' => [
              'usuario.nombres',
              'driverCategory.name',
              'credits',
              'porcent:percent',
              'code',
              'active:boolean'
           ]
        ]) ?>
        <h4>Informacion del auto</h4>
        <?= $this->render('_detail_list', [
           'model' => $model
        ]) ?>
      </div>
      <div class="col-md-6">
        <?php $form = \yii\widgets\ActiveForm::begin([
           'action' => ['view-driver', 'id' => $model->id]
        ]) ?>
        <?= $form->field($model, 'departamento_id')->dropDownList(
           \yii\helpers\ArrayHelper::map(\app\models\Departamento::find()
              ->orderBy('nombre')->all(), 'id', 'nombre')
        ) ?>
        <?= \yii\helpers\Html::submitButton('Guardar', ['class' => 'btn btn-info']) ?>
        <?php \yii\widgets\ActiveForm::end() ?>
        <h1>
          Cambio de contraseña
        </h1>
        <?= Html::beginForm(['update-password', 'id' => $model->id]) ?>
        <?= Html::textInput('password', '', ['minlenght' => 6, 'required' => true, 'class' => 'form-control']) ?>
        <?= Html::submitButton('Confirmar') ?>
        <?= Html::endForm() ?>
      </div>
      <div class="col-lg-12">
        <h4>Compras de credito confirmadas</h4>
        <?= \yii\grid\GridView::widget([
           'dataProvider' => new \yii\data\ActiveDataProvider([
              'query' => $model->getDriverPurchases()
                 ->where(['driver_purchase.is_confirm' => true])
           ])
        ]) ?>
      </div>
    </div>
  </div>

<?php
$this->registerJsFile('https://www.gstatic.com/firebasejs/5.8.4/firebase.js', [
   'position' => $this::POS_HEAD
]);
$this->registerJs('
 var config = {
    apiKey: "AIzaSyAf3s1qepgZT9W6BYv5NkhXw5IMONrsDCE",
    authDomain: "taxidriver-23cbd.firebaseapp.com",
    databaseURL: "https://taxidriver-23cbd.firebaseio.com",
    projectId: "taxidriver-23cbd",
    storageBucket: "taxidriver-23cbd.appspot.com",
    messagingSenderId: "927678779355"
  };
  firebase.initializeApp(config);', $this::POS_HEAD);
$this->registerJsFile("@web/js/update-password-firebase.js", [
   'depends' => [JqueryAsset::class]
]) ?>